[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/api/process"
  to     = "https://prod-25.northcentralus.logic.azure.com:443/workflows/13d983f2244d4d419aa201e9c2bd829e/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Or-_9WlR9WPDq-9hVM1HehYq1WKbUKsxllPo15r4NOg"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/review"
  to     = "https://prod-19.northcentralus.logic.azure.com:443/workflows/3e0a05fc36cb494aa05761749d498215/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=31MCUjJDAAP5VdOpRargnTR3hoSds8VOGs9-DGY8do4"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200